name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run content check
        run: npm run check

  check-zola:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zola
        run: |
          ZOLA_VERSION=0.17.2
          curl -L https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin
      - name: Check links
        run: zola check

  check-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install Zola
        run: |
          ZOLA_VERSION=0.17.2
          curl -L https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin
      - name: Build the project
        run: npm run build
      - name: Run Lighthouse CI
        run: lhci autorun
